<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity\CreateTermsAndConditions;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-termsAndConditions
 */
class Response extends Entity
{
    /**
     * Unique identifier of Terms and Conditions.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example aeca2ac3-1d03-4f17-855b-19767f9c4586
     */
    public function getTermsAndConditionsId(): ?string
    {
        return $this->_getString('termsAndConditionsId');
    }

    /**
     * Unique identifier of Terms and Conditions.
     *
     * @optional
     *
     * @return $this
     *
     * @example aeca2ac3-1d03-4f17-855b-19767f9c4586
     */
    public function setTermsAndConditionsId(?string $value): self
    {
        return $value === null ? $this->_unset('termsAndConditionsId') : $this->_set('termsAndConditionsId', $value);
    }
}
