<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity\FindOperations;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-operations
 */
class Response extends Entity
{
    /**
     * Array containing the operations list.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @return \MLocati\Nexi\Entity\Operation[]|null
     */
    public function getOperations(): ?array
    {
        return $this->_getEntityArray('operations', \MLocati\Nexi\Entity\Operation::class);
    }

    /**
     * Array containing the operations list.
     *
     * @param \MLocati\Nexi\Entity\Operation[]|null $value
     *
     * @optional
     *
     * @return $this
     */
    public function setOperations(?array $value): self
    {
        return $value === null ? $this->_unset('operations') : $this->_setEntityArray('operations', \MLocati\Nexi\Entity\Operation::class, $value);
    }
}
