<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity\FindTermsAndConditionsById;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-terms_and_conditions-termsAndConditionsId
 */
class Response extends Entity
{
    /**
     * Free label to let the merchant identify the Terms and Conditions version for audit purposes.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example Grand Hotel Mississipi selling conditions v01
     */
    public function getName(): ?string
    {
        return $this->_getString('name');
    }

    /**
     * Free label to let the merchant identify the Terms and Conditions version for audit purposes.
     *
     * @optional
     *
     * @return $this
     *
     * @example Grand Hotel Mississipi selling conditions v01
     */
    public function setName(?string $value): self
    {
        return $value === null ? $this->_unset('name') : $this->_set('name', $value);
    }

    /**
     * Timestamp related to creation date for Terms and Conditions.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example 2023-03-16T00:00:00.000Z
     */
    public function getTecCreationDate(): ?string
    {
        return $this->_getString('tecCreationDate');
    }

    /**
     * Timestamp related to creation date for Terms and Conditions.
     *
     * @optional
     *
     * @return $this
     *
     * @example 2023-03-16T00:00:00.000Z
     */
    public function setTecCreationDate(?string $value): self
    {
        return $value === null ? $this->_unset('tecCreationDate') : $this->_set('tecCreationDate', $value);
    }

    /**
     * Array of Terms and Conditions in multiple languages.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @return \MLocati\Nexi\XPayWeb\Entity\TermsAndConditions[]|null
     */
    public function getTermsAndConditions(): ?array
    {
        return $this->_getEntityArray('termsAndConditions', \MLocati\Nexi\XPayWeb\Entity\TermsAndConditions::class);
    }

    /**
     * Array of Terms and Conditions in multiple languages.
     *
     * @param \MLocati\Nexi\XPayWeb\Entity\TermsAndConditions[]|null $value
     *
     * @optional
     *
     * @return $this
     */
    public function setTermsAndConditions(?array $value): self
    {
        return $value === null ? $this->_unset('termsAndConditions') : $this->_setEntityArray('termsAndConditions', \MLocati\Nexi\XPayWeb\Entity\TermsAndConditions::class, $value);
    }

    /**
     * Unique identifier of Terms and Conditions.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example aeca2ac3-1d03-4f17-855b-19767f9c4586
     */
    public function getTermsAndConditionsId(): ?string
    {
        return $this->_getString('termsAndConditionsId');
    }

    /**
     * Unique identifier of Terms and Conditions.
     *
     * @optional
     *
     * @return $this
     *
     * @example aeca2ac3-1d03-4f17-855b-19767f9c4586
     */
    public function setTermsAndConditionsId(?string $value): self
    {
        return $value === null ? $this->_unset('termsAndConditionsId') : $this->_set('termsAndConditionsId', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
