<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity\CardVerification;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-orders-card_verification
 */
class Request extends Entity
{
    /**
     * Object containing the detail of the order.
     *
     * @required
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getOrder(): ?\MLocati\Nexi\Entity\Order
    {
        return $this->_getEntity('order', \MLocati\Nexi\Entity\Order::class);
    }

    /**
     * @see \MLocati\Nexi\Entity\CardVerification\Request::getOrder()
     */
    public function getOrCreateOrder(): \MLocati\Nexi\Entity\Order
    {
        $result = $this->getOrder();
        if ($result === null) {
            $this->setOrder($result = new \MLocati\Nexi\Entity\Order());
        }

        return $result;
    }

    /**
     * Object containing the detail of the order.
     *
     * @required
     *
     * @return $this
     */
    public function setOrder(\MLocati\Nexi\Entity\Order $value): self
    {
        return $this->_set('order', $value);
    }

    /**
     * Object containing the details of the payment card.
     *
     * @required
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getCard(): ?\MLocati\Nexi\Entity\Card
    {
        return $this->_getEntity('card', \MLocati\Nexi\Entity\Card::class);
    }

    /**
     * @see \MLocati\Nexi\Entity\CardVerification\Request::getCard()
     */
    public function getOrCreateCard(): \MLocati\Nexi\Entity\Card
    {
        $result = $this->getCard();
        if ($result === null) {
            $this->setCard($result = new \MLocati\Nexi\Entity\Card());
        }

        return $result;
    }

    /**
     * Object containing the details of the payment card.
     *
     * @required
     *
     * @return $this
     */
    public function setCard(\MLocati\Nexi\Entity\Card $value): self
    {
        return $this->_set('card', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
            'order' => true,
            'card' => true,
        ];
    }
}
