<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-reservations#tab_response
 * @see https://developer.nexi.it/en/api/get-reservations-reservationId#tab_response
 * @see https://developer.nexi.it/en/api/post-reservations#tab_body
 */
class CancellationCondition extends Entity
{
    /**
     * The value of the selected data type.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example 2
     */
    public function getDataTypeValue(): ?string
    {
        return $this->_getString('dataTypeValue');
    }

    /**
     * The value of the selected data type.
     *
     * @optional
     *
     * @return $this
     *
     * @example 2
     */
    public function setDataTypeValue(?string $value): self
    {
        return $value === null ? $this->_unset('dataTypeValue') : $this->_set('dataTypeValue', $value);
    }

    /**
     * The value for the penalty amount or percentage of refund.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example 5000
     */
    public function getValue(): ?string
    {
        return $this->_getString('value');
    }

    /**
     * The value for the penalty amount or percentage of refund.
     *
     * @optional
     *
     * @return $this
     *
     * @example 5000
     */
    public function setValue(?string $value): self
    {
        return $value === null ? $this->_unset('value') : $this->_set('value', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
