<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-delay_charges
 * @see https://developer.nexi.it/en/api/post-incrementals
 * @see https://developer.nexi.it/en/api/post-no_shows
 */
class ChangeAmountRequest extends Entity
{
    /**
     * Operation ID to be incremented.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 3470744
     */
    public function getOriginalOperationId(): ?string
    {
        return $this->_getString('originalOperationId');
    }

    /**
     * Operation ID to be incremented.
     *
     * @optional
     *
     * @return $this
     *
     * @example 3470744
     */
    public function setOriginalOperationId(?string $value): self
    {
        return $value === null ? $this->_unset('originalOperationId') : $this->_set('originalOperationId', $value);
    }

    /**
     * Incremental amount in smallest currency unit.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 100
     */
    public function getAmount(): ?string
    {
        return $this->_getString('amount');
    }

    /**
     * Incremental amount in smallest currency unit.
     *
     * @optional
     *
     * @return $this
     *
     * @example 100
     */
    public function setAmount(?string $value): self
    {
        return $value === null ? $this->_unset('amount') : $this->_set('amount', $value);
    }

    /**
     * Transaction currency. ISO 4217 alphabetic code.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example EUR
     */
    public function getCurrency(): ?string
    {
        return $this->_getString('currency');
    }

    /**
     * Transaction currency. ISO 4217 alphabetic code.
     *
     * @optional
     *
     * @return $this
     *
     * @example EUR
     */
    public function setCurrency(?string $value): self
    {
        return $value === null ? $this->_unset('currency') : $this->_set('currency', $value);
    }

    /**
     * Operation description.
     *
     * @optional
     * Maximum length: 255
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example Hotel reservation extended.
     * @example Damaged TV in hotel room.
     * @example As per the hotel policy.
     */
    public function getDescription(): ?string
    {
        return $this->_getString('description');
    }

    /**
     * Operation description.
     *
     * @optional
     * Maximum length: 255
     *
     * @return $this
     *
     * @example Hotel reservation extended.
     * @example Damaged TV in hotel room.
     * @example As per the hotel policy.
     */
    public function setDescription(?string $value): self
    {
        return $value === null ? $this->_unset('description') : $this->_set('description', $value);
    }
}
