<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-custom_fields-customFieldId
 * @see https://developer.nexi.it/en/api/post-custom_fields
 */
class CustomFieldDetails extends Entity
{
    /**
     * Structure identifier unique in the merchant domain.
     *
     * @optional
     * Maximum length: 36
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example 99a172e5-423c-4648-9895-4cb5d1d43134
     */
    public function getStructureId(): ?string
    {
        return $this->_getString('structureId');
    }

    /**
     * Structure identifier unique in the merchant domain.
     *
     * @optional
     * Maximum length: 36
     *
     * @return $this
     *
     * @example 99a172e5-423c-4648-9895-4cb5d1d43134
     */
    public function setStructureId(?string $value): self
    {
        return $value === null ? $this->_unset('structureId') : $this->_set('structureId', $value);
    }

    /**
     * The custom fields ordering.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example 1
     */
    public function getCustomFieldOrd(): ?int
    {
        return $this->_getInt('customFieldOrd');
    }

    /**
     * The custom fields ordering.
     *
     * @optional
     *
     * @return $this
     *
     * @example 1
     */
    public function setCustomFieldOrd(?int $value): self
    {
        return $value === null ? $this->_unset('customFieldOrd') : $this->_set('customFieldOrd', $value);
    }

    /**
     * The title used for identify the custom field.
     *
     * @optional
     * Maximum length: 50
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example Animali domestici
     */
    public function getCustomFieldTitle(): ?string
    {
        return $this->_getString('customFieldTitle');
    }

    /**
     * The title used for identify the custom field.
     *
     * @optional
     * Maximum length: 50
     *
     * @return $this
     *
     * @example Animali domestici
     */
    public function setCustomFieldTitle(?string $value): self
    {
        return $value === null ? $this->_unset('customFieldTitle') : $this->_set('customFieldTitle', $value);
    }

    /**
     * The custom field status.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     */
    public function getCustomFieldEnabled(): ?bool
    {
        return $this->_getBool('customFieldEnabled');
    }

    /**
     * The custom field status.
     *
     * @optional
     *
     * @return $this
     */
    public function setCustomFieldEnabled(?bool $value): self
    {
        return $value === null ? $this->_unset('customFieldEnabled') : $this->_set('customFieldEnabled', $value);
    }

    /**
     * Array of labels in multiple languages.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @return \MLocati\Nexi\XPayWeb\Entity\CustomFieldTranslation[]|null
     */
    public function getCustomFieldTranslations(): ?array
    {
        return $this->_getEntityArray('customFieldTranslations', CustomFieldTranslation::class);
    }

    /**
     * Array of labels in multiple languages.
     *
     * @param \MLocati\Nexi\XPayWeb\Entity\CustomFieldTranslation[]|null $value
     *
     * @optional
     *
     * @return $this
     */
    public function setCustomFieldTranslations(?array $value): self
    {
        return $value === null ? $this->_unset('customFieldTranslations') : $this->_setEntityArray('customFieldTranslations', CustomFieldTranslation::class, $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
