<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-build-state
 * @see https://developer.nexi.it/en/api/get-contracts-customers-customerId
 * @see https://developer.nexi.it/en/api/get-custom_fields-customFieldId
 * @see https://developer.nexi.it/en/api/get-operations
 * @see https://developer.nexi.it/en/api/get-operations-operationId
 * @see https://developer.nexi.it/en/api/get-operations-operationId-actions
 * @see https://developer.nexi.it/en/api/get-orders
 * @see https://developer.nexi.it/en/api/get-orders-orderId
 * @see https://developer.nexi.it/en/api/get-reservations
 * @see https://developer.nexi.it/en/api/get-reservations-reservationId
 * @see https://developer.nexi.it/en/api/get-services
 * @see https://developer.nexi.it/en/api/get-structure_conditions-structureConditionId
 * @see https://developer.nexi.it/en/api/get-structure_conditions-structureConditionId-pdf
 * @see https://developer.nexi.it/en/api/get-structure_conditions-structures-structureid
 * @see https://developer.nexi.it/en/api/get-structures
 * @see https://developer.nexi.it/en/api/get-structures-structureId
 * @see https://developer.nexi.it/en/api/get-terms_and_conditions-termsAndConditionsId
 * @see https://developer.nexi.it/en/api/post-build-cancel
 * @see https://developer.nexi.it/en/api/post-build-finalize-payment
 * @see https://developer.nexi.it/en/api/post-contracts-contractId-deactivation
 * @see https://developer.nexi.it/en/api/post-custom_fields
 * @see https://developer.nexi.it/en/api/post-delay_charges
 * @see https://developer.nexi.it/en/api/post-delaycharge_validation
 * @see https://developer.nexi.it/en/api/post-incremental_validation
 * @see https://developer.nexi.it/en/api/post-incrementals
 * @see https://developer.nexi.it/en/api/post-no_shows
 * @see https://developer.nexi.it/en/api/post-noshow_validation
 * @see https://developer.nexi.it/en/api/post-operations-operationId-cancels
 * @see https://developer.nexi.it/en/api/post-operations-operationId-captures
 * @see https://developer.nexi.it/en/api/post-operations-operationId-refunds
 * @see https://developer.nexi.it/en/api/post-orders-2steps-init
 * @see https://developer.nexi.it/en/api/post-orders-2steps-payment
 * @see https://developer.nexi.it/en/api/post-orders-3steps-init
 * @see https://developer.nexi.it/en/api/post-orders-3steps-payment
 * @see https://developer.nexi.it/en/api/post-orders-3steps-validation
 * @see https://developer.nexi.it/en/api/post-orders-build
 * @see https://developer.nexi.it/en/api/post-orders-card_verification
 * @see https://developer.nexi.it/en/api/post-orders-hpp
 * @see https://developer.nexi.it/en/api/post-orders-mit
 * @see https://developer.nexi.it/en/api/post-orders-moto
 * @see https://developer.nexi.it/en/api/post-orders-paybylink
 * @see https://developer.nexi.it/en/api/post-orders-virtual_card
 * @see https://developer.nexi.it/en/api/post-paybylink-linkId-cancels
 * @see https://developer.nexi.it/en/api/post-payment_methods
 * @see https://developer.nexi.it/en/api/post-reservation-reservationId-mit
 * @see https://developer.nexi.it/en/api/post-reservations
 * @see https://developer.nexi.it/en/api/post-reservations-reservationId-paybylink
 * @see https://developer.nexi.it/en/api/post-services
 * @see https://developer.nexi.it/en/api/post-structure_conditions
 * @see https://developer.nexi.it/en/api/post-structure_conditions-structureConditionId-cancels
 * @see https://developer.nexi.it/en/api/post-structures
 * @see https://developer.nexi.it/en/api/post-termsAndConditions
 * @see https://developer.nexi.it/en/api/post-terms_and_conditions-termsAndConditionsId-cancels
 */
class Errors extends Entity
{
    /**
     * Array containing the errors list. The possible values are shown in the table Error codes.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @return \MLocati\Nexi\XPayWeb\Entity\Error[]|null
     */
    public function getErrors(): ?array
    {
        return $this->_getEntityArray('errors', Error::class);
    }

    /**
     * Array containing the errors list. The possible values are shown in the table Error codes.
     *
     * @param \MLocati\Nexi\XPayWeb\Entity\Error[]|null $value
     *
     * @optional
     *
     * @return $this
     */
    public function setErrors(?array $value): self
    {
        return $value === null ? $this->_unset('errors') : $this->_setEntityArray('errors', Error::class, $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
