<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-build-state#tab_response
 * @see https://developer.nexi.it/en/api/get-contracts-customers-customerId#tab_response
 * @see https://developer.nexi.it/en/api/get-custom_fields-customFieldId#tab_response
 * @see https://developer.nexi.it/en/api/get-operations#tab_response
 * @see https://developer.nexi.it/en/api/get-operations-operationId#tab_response
 * @see https://developer.nexi.it/en/api/get-operations-operationId-actions#tab_response
 * @see https://developer.nexi.it/en/api/get-orders#tab_response
 * @see https://developer.nexi.it/en/api/get-orders-orderId#tab_response
 * @see https://developer.nexi.it/en/api/get-reservations#tab_response
 * @see https://developer.nexi.it/en/api/get-reservations-reservationId#tab_response
 * @see https://developer.nexi.it/en/api/get-services#tab_response
 * @see https://developer.nexi.it/en/api/get-structure_conditions-structureConditionId#tab_response
 * @see https://developer.nexi.it/en/api/get-structure_conditions-structureConditionId-pdf#tab_response
 * @see https://developer.nexi.it/en/api/get-structure_conditions-structures-structureid#tab_response
 * @see https://developer.nexi.it/en/api/get-structures#tab_response
 * @see https://developer.nexi.it/en/api/get-structures-structureId#tab_response
 * @see https://developer.nexi.it/en/api/get-terms_and_conditions-termsAndConditionsId#tab_response
 * @see https://developer.nexi.it/en/api/notifica#tab_body
 * @see https://developer.nexi.it/en/api/post-build-cancel#tab_response
 * @see https://developer.nexi.it/en/api/post-build-finalize-payment#tab_response
 * @see https://developer.nexi.it/en/api/post-contracts-contractId-deactivation#tab_response
 * @see https://developer.nexi.it/en/api/post-custom_fields#tab_response
 * @see https://developer.nexi.it/en/api/post-delay_charges#tab_response
 * @see https://developer.nexi.it/en/api/post-delaycharge_validation#tab_response
 * @see https://developer.nexi.it/en/api/post-incremental_validation#tab_response
 * @see https://developer.nexi.it/en/api/post-incrementals#tab_response
 * @see https://developer.nexi.it/en/api/post-no_shows#tab_response
 * @see https://developer.nexi.it/en/api/post-noshow_validation#tab_response
 * @see https://developer.nexi.it/en/api/post-operations-operationId-cancels#tab_response
 * @see https://developer.nexi.it/en/api/post-operations-operationId-captures#tab_response
 * @see https://developer.nexi.it/en/api/post-operations-operationId-refunds#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-2steps-init#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-2steps-payment#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-3steps-init#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-3steps-payment#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-3steps-validation#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-build#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-card_verification#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-hpp#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-mit#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-moto#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-paybylink#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-virtual_card#tab_response
 * @see https://developer.nexi.it/en/api/post-paybylink-linkId-cancels#tab_response
 * @see https://developer.nexi.it/en/api/post-payment_methods#tab_response
 * @see https://developer.nexi.it/en/api/post-reservation-reservationId-mit#tab_response
 * @see https://developer.nexi.it/en/api/post-reservations#tab_response
 * @see https://developer.nexi.it/en/api/post-reservations-reservationId-paybylink#tab_response
 * @see https://developer.nexi.it/en/api/post-services#tab_response
 * @see https://developer.nexi.it/en/api/post-structure_conditions#tab_response
 * @see https://developer.nexi.it/en/api/post-structure_conditions-structureConditionId-cancels#tab_response
 * @see https://developer.nexi.it/en/api/post-structures#tab_response
 * @see https://developer.nexi.it/en/api/post-termsAndConditions#tab_response
 * @see https://developer.nexi.it/en/api/post-terms_and_conditions-termsAndConditionsId-cancels#tab_response
 */
class Error extends Entity
{
    /**
     * Error code.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example GW0001
     * @example TRA001
     */
    public function getCode(): ?string
    {
        return $this->_getString('code');
    }

    /**
     * Error code.
     *
     * @optional
     *
     * @return $this
     *
     * @example GW0001
     * @example TRA001
     */
    public function setCode(?string $value): self
    {
        return $value === null ? $this->_unset('code') : $this->_set('code', $value);
    }

    /**
     * Error description.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example Invalid merchant URL
     * @example 3DS warning
     */
    public function getDescription(): ?string
    {
        return $this->_getString('description');
    }

    /**
     * Error description.
     *
     * @optional
     *
     * @return $this
     *
     * @example Invalid merchant URL
     * @example 3DS warning
     */
    public function setDescription(?string $value): self
    {
        return $value === null ? $this->_unset('description') : $this->_set('description', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
