<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-build-state#tab_response
 * @see https://developer.nexi.it/en/api/post-orders-build#tab_response
 */
class Field extends Entity
{
    /**
     * Type of field, possible values:
     * - ACTION: field that requires an action by the cardholder on the iframe, in this case the click on the component.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example ACTION
     */
    public function getType(): ?string
    {
        return $this->_getString('type');
    }

    /**
     * Type of field, possible values:
     * - ACTION: field that requires an action by the cardholder on the iframe, in this case the click on the component.
     *
     * @optional
     *
     * @return $this
     *
     * @example ACTION
     */
    public function setType(?string $value): self
    {
        return $value === null ? $this->_unset('type') : $this->_set('type', $value);
    }

    /**
     * Field class, possible values:
     * - APM
     * - CARD
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example CARD
     */
    public function getClass(): ?string
    {
        return $this->_getString('class');
    }

    /**
     * Field class, possible values:
     * - APM
     * - CARD
     *
     * @optional
     *
     * @return $this
     *
     * @example CARD
     */
    public function setClass(?string $value): self
    {
        return $value === null ? $this->_unset('class') : $this->_set('class', $value);
    }

    /**
     * Field identifier.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example PAY_WITH_CARD
     */
    public function getId(): ?string
    {
        return $this->_getString('id');
    }

    /**
     * Field identifier.
     *
     * @optional
     *
     * @return $this
     *
     * @example PAY_WITH_CARD
     */
    public function setId(?string $value): self
    {
        return $value === null ? $this->_unset('id') : $this->_set('id', $value);
    }

    /**
     * Iframe URL dedicated to the payment method.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example https:///field.html?id=CARDHOLDER_NAME&sid=052211e8-54c8-4e0a-8402-e10bcb8ff264
     */
    public function getSrc(): ?string
    {
        return $this->_getString('src');
    }

    /**
     * Iframe URL dedicated to the payment method.
     *
     * @optional
     *
     * @return $this
     *
     * @example https:///field.html?id=CARDHOLDER_NAME&sid=052211e8-54c8-4e0a-8402-e10bcb8ff264
     */
    public function setSrc(?string $value): self
    {
        return $value === null ? $this->_unset('src') : $this->_set('src', $value);
    }
}
