<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-reservations#tab_response
 * @see https://developer.nexi.it/en/api/get-reservations-reservationId#tab_response
 * @see https://developer.nexi.it/en/api/post-reservations#tab_body
 */
class Installment extends Entity
{
    /**
     * Installment time.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 2022-09-01
     */
    public function getDate(): ?string
    {
        return $this->_getString('date');
    }

    /**
     * Installment time.
     *
     * @optional
     *
     * @return $this
     *
     * @example 2022-09-01
     */
    public function setDate(?string $value): self
    {
        return $value === null ? $this->_unset('date') : $this->_set('date', $value);
    }

    /**
     * Installment amount.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 350
     */
    public function getAmount(): ?string
    {
        return $this->_getString('amount');
    }

    /**
     * Installment amount.
     *
     * @optional
     *
     * @return $this
     *
     * @example 350
     */
    public function setAmount(?string $value): self
    {
        return $value === null ? $this->_unset('amount') : $this->_set('amount', $value);
    }

    /**
     * Possible values:
     * - AUTOMATIC: installments will be made automatically by XPay.
     * - MANUAL: installments will be made manually by the merchant.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example AUTOMATIC
     */
    public function getType(): ?string
    {
        return $this->_getString('type');
    }

    /**
     * Possible values:
     * - AUTOMATIC: installments will be made automatically by XPay.
     * - MANUAL: installments will be made manually by the merchant.
     *
     * @optional
     *
     * @return $this
     *
     * @example AUTOMATIC
     */
    public function setType(?string $value): self
    {
        return $value === null ? $this->_unset('type') : $this->_set('type', $value);
    }
}
