<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-orders-2steps-init
 * @see https://developer.nexi.it/en/api/post-orders-3steps-init
 */
class MultiStepInitRequest extends Entity
{
    /**
     * Object containing the detail of the order.
     *
     * @required
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getOrder(): ?Order
    {
        return $this->_getEntity('order', Order::class);
    }

    /**
     * @see \MLocati\Nexi\Entity\MultiStepInitRequest::getOrder()
     */
    public function getOrCreateOrder(): Order
    {
        $result = $this->getOrder();
        if ($result === null) {
            $this->setOrder($result = new Order());
        }

        return $result;
    }

    /**
     * Object containing the detail of the order.
     *
     * @required
     *
     * @return $this
     */
    public function setOrder(Order $value): self
    {
        return $this->_set('order', $value);
    }

    /**
     * Object containing the details of the payment card.
     *
     * @required
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getCard(): ?Card
    {
        return $this->_getEntity('card', Card::class);
    }

    /**
     * @see \MLocati\Nexi\Entity\MultiStepInitRequest::getCard()
     */
    public function getOrCreateCard(): Card
    {
        $result = $this->getCard();
        if ($result === null) {
            $this->setCard($result = new Card());
        }

        return $result;
    }

    /**
     * Object containing the details of the payment card.
     *
     * @required
     *
     * @return $this
     */
    public function setCard(Card $value): self
    {
        return $this->_set('card', $value);
    }

    /**
     * Object containing the detail of the occurrence.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getRecurrence(): ?Recurrence
    {
        return $this->_getEntity('recurrence', Recurrence::class);
    }

    /**
     * @see \MLocati\Nexi\Entity\MultiStepInitRequest::getRecurrence()
     */
    public function getOrCreateRecurrence(): Recurrence
    {
        $result = $this->getRecurrence();
        if ($result === null) {
            $this->setRecurrence($result = new Recurrence());
        }

        return $result;
    }

    /**
     * Object containing the detail of the occurrence.
     *
     * @optional
     *
     * @return $this
     */
    public function setRecurrence(?Recurrence $value): self
    {
        return $value === null ? $this->_unset('recurrence') : $this->_set('recurrence', $value);
    }

    /**
     * NO_PREFERENCE, CHALLENGE_REQUESTED
     *
     * @default NO_PREFERENCE
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example NO_PREFERENCE
     */
    public function getExemptions(): ?string
    {
        return $this->_getString('exemptions');
    }

    /**
     * NO_PREFERENCE, CHALLENGE_REQUESTED
     *
     * @default NO_PREFERENCE
     *
     * @optional
     *
     * @return $this
     *
     * @example NO_PREFERENCE
     */
    public function setExemptions(?string $value): self
    {
        return $value === null ? $this->_unset('exemptions') : $this->_set('exemptions', $value);
    }
}
