<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-orders-2steps-init
 * @see https://developer.nexi.it/en/api/post-orders-3steps-init
 */
class MultiStepInitResponse extends Entity
{
    /**
     * Object containing operation detail.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getOperation(): ?Operation
    {
        return $this->_getEntity('operation', Operation::class);
    }

    /**
     * Object containing operation detail.
     *
     * @optional
     *
     * @return $this
     */
    public function setOperation(?Operation $value): self
    {
        return $value === null ? $this->_unset('operation') : $this->_set('operation', $value);
    }

    /**
     * 3DS Server output of 3DS enrollment check for the given card.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example ENROLLED
     */
    public function getThreeDSEnrollmentStatus(): ?string
    {
        return $this->_getString('threeDSEnrollmentStatus');
    }

    /**
     * 3DS Server output of 3DS enrollment check for the given card.
     *
     * @optional
     *
     * @return $this
     *
     * @example ENROLLED
     */
    public function setThreeDSEnrollmentStatus(?string $value): self
    {
        return $value === null ? $this->_unset('threeDSEnrollmentStatus') : $this->_set('threeDSEnrollmentStatus', $value);
    }

    /**
     * Information to be passed in the 3DS authentication phase. Needed for 3DS1. This value must be passed in the form for triggerring the authentication step described in '#/components/schemas/ChallengeRequest'.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example s51s35g1se3rg16r1gs35d1g53d1g813531818
     */
    public function getThreeDSAuthRequest(): ?string
    {
        return $this->_getString('threeDSAuthRequest');
    }

    /**
     * Information to be passed in the 3DS authentication phase. Needed for 3DS1. This value must be passed in the form for triggerring the authentication step described in '#/components/schemas/ChallengeRequest'.
     *
     * @optional
     *
     * @return $this
     *
     * @example s51s35g1se3rg16r1gs35d1g53d1g813531818
     */
    public function setThreeDSAuthRequest(?string $value): self
    {
        return $value === null ? $this->_unset('threeDSAuthRequest') : $this->_set('threeDSAuthRequest', $value);
    }

    /**
     * URL for posting the next step from the cardholder browser. The form application/x-www-form-urlencoded must include the fields described in '#/components/schemas/ChallengeRequest' The cardholder will be redirected to the 3DS authentication flow.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example http://www.example.com/payment/nextStep
     */
    public function getThreeDSAuthUrl(): ?string
    {
        return $this->_getString('threeDSAuthUrl');
    }

    /**
     * URL for posting the next step from the cardholder browser. The form application/x-www-form-urlencoded must include the fields described in '#/components/schemas/ChallengeRequest' The cardholder will be redirected to the 3DS authentication flow.
     *
     * @optional
     *
     * @return $this
     *
     * @example http://www.example.com/payment/nextStep
     */
    public function setThreeDSAuthUrl(?string $value): self
    {
        return $value === null ? $this->_unset('threeDSAuthUrl') : $this->_set('threeDSAuthUrl', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
