<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-orders-paybylink
 * @see https://developer.nexi.it/en/api/post-reservations-reservationId-paybylink
 */
class PayByLinkResponse extends Entity
{
    /**
     * Object containing the payment link detail.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     */
    public function getPaymentLink(): ?PaymentLink
    {
        return $this->_getEntity('paymentLink', PaymentLink::class);
    }

    /**
     * Object containing the payment link detail.
     *
     * @optional
     *
     * @return $this
     */
    public function setPaymentLink(?PaymentLink $value): self
    {
        return $value === null ? $this->_unset('paymentLink') : $this->_set('paymentLink', $value);
    }

    /**
     * Token which may be used for validating the notifications related to this payment.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example 2f0ea5059b41414ca3744fe672327d85
     */
    public function getSecurityToken(): ?string
    {
        return $this->_getString('securityToken');
    }

    /**
     * Token which may be used for validating the notifications related to this payment.
     *
     * @optional
     *
     * @return $this
     *
     * @example 2f0ea5059b41414ca3744fe672327d85
     */
    public function setSecurityToken(?string $value): self
    {
        return $value === null ? $this->_unset('securityToken') : $this->_set('securityToken', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
