<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-delaycharge_validation
 * @see https://developer.nexi.it/en/api/post-incremental_validation
 * @see https://developer.nexi.it/en/api/post-noshow_validation
 */
class ReservationValidation extends Entity
{
    /**
     * Reservation Id for which the no show is needed to validate.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example btid12345678
     */
    public function getReservationId(): ?string
    {
        return $this->_getString('reservationId');
    }

    /**
     * Reservation Id for which the no show is needed to validate.
     *
     * @optional
     *
     * @return $this
     *
     * @example btid12345678
     */
    public function setReservationId(?string $value): self
    {
        return $value === null ? $this->_unset('reservationId') : $this->_set('reservationId', $value);
    }

    /**
     * No show amount in smallest currency unit.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 100
     */
    public function getAmount(): ?string
    {
        return $this->_getString('amount');
    }

    /**
     * No show amount in smallest currency unit.
     *
     * @optional
     *
     * @return $this
     *
     * @example 100
     */
    public function setAmount(?string $value): self
    {
        return $value === null ? $this->_unset('amount') : $this->_set('amount', $value);
    }

    /**
     * Transaction currency. ISO 4217 alphabetic code.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example EUR
     */
    public function getCurrency(): ?string
    {
        return $this->_getString('currency');
    }

    /**
     * Transaction currency. ISO 4217 alphabetic code.
     *
     * @optional
     *
     * @return $this
     *
     * @example EUR
     */
    public function setCurrency(?string $value): self
    {
        return $value === null ? $this->_unset('currency') : $this->_set('currency', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
