<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-terms_and_conditions-termsAndConditionsId#tab_response
 * @see https://developer.nexi.it/en/api/post-termsAndConditions#tab_body
 */
class TermsAndConditions extends Entity
{
    /**
     * Language to be used on the Terms and Conditions labels, ISO 639-2.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example eng
     */
    public function getLanguage(): ?string
    {
        return $this->_getString('language');
    }

    /**
     * Language to be used on the Terms and Conditions labels, ISO 639-2.
     *
     * @optional
     *
     * @return $this
     *
     * @example eng
     */
    public function setLanguage(?string $value): self
    {
        return $value === null ? $this->_unset('language') : $this->_set('language', $value);
    }

    /**
     * Text to be showed beside the checkmark of acceptance.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example Confirm to accept terms and conditions
     */
    public function getCheckMarkLabel(): ?string
    {
        return $this->_getString('checkMarkLabel');
    }

    /**
     * Text to be showed beside the checkmark of acceptance.
     *
     * @optional
     *
     * @return $this
     *
     * @example Confirm to accept terms and conditions
     */
    public function setCheckMarkLabel(?string $value): self
    {
        return $value === null ? $this->_unset('checkMarkLabel') : $this->_set('checkMarkLabel', $value);
    }

    /**
     * Text of the hyperlink of the T&C detailed text.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example Property Condition
     */
    public function getLinkLabel(): ?string
    {
        return $this->_getString('linkLabel');
    }

    /**
     * Text of the hyperlink of the T&C detailed text.
     *
     * @optional
     *
     * @return $this
     *
     * @example Property Condition
     */
    public function setLinkLabel(?string $value): self
    {
        return $value === null ? $this->_unset('linkLabel') : $this->_set('linkLabel', $value);
    }

    /**
     * Text of the terms and conditions in html format, encoded in Base64.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example PGRpdj48aDM+Q29uZGl0aW9uPGgzPjxwPlRoZSBub24tcmVmdW5kYWJsZSByYXRlIHJlcXVpcmVzIHRoZSBmdWxsIGFtb3VudCB0byBiZSBjaGFyZ2VkIGF0IHRoZSB0aW1lIG9mIGJvb2tpbmc8L3A+PGRpdj4=
     */
    public function getText(): ?string
    {
        return $this->_getString('text');
    }

    /**
     * Text of the terms and conditions in html format, encoded in Base64.
     *
     * @optional
     *
     * @return $this
     *
     * @example PGRpdj48aDM+Q29uZGl0aW9uPGgzPjxwPlRoZSBub24tcmVmdW5kYWJsZSByYXRlIHJlcXVpcmVzIHRoZSBmdWxsIGFtb3VudCB0byBiZSBjaGFyZ2VkIGF0IHRoZSB0aW1lIG9mIGJvb2tpbmc8L3A+PGRpdj4=
     */
    public function setText(?string $value): self
    {
        return $value === null ? $this->_unset('text') : $this->_set('text', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
