<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-orders-3steps-validation#tab_response
 */
class ThreeDSAuthResult extends Entity
{
    /**
     * Completed for the 3-steps flow, obtained from the validation phase.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example AAIBBjhkYQAAAAAKl4FHdAAAAAA=
     */
    public function getAuthenticationValue(): ?string
    {
        return $this->_getString('authenticationValue');
    }

    /**
     * Completed for the 3-steps flow, obtained from the validation phase.
     *
     * @optional
     *
     * @return $this
     *
     * @example AAIBBjhkYQAAAAAKl4FHdAAAAAA=
     */
    public function setAuthenticationValue(?string $value): self
    {
        return $value === null ? $this->_unset('authenticationValue') : $this->_set('authenticationValue', $value);
    }

    /**
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getCavvAlgorithm(): ?string
    {
        return $this->_getString('cavvAlgorithm');
    }

    /**
     * @optional
     *
     * @return $this
     */
    public function setCavvAlgorithm(?string $value): self
    {
        return $value === null ? $this->_unset('cavvAlgorithm') : $this->_set('cavvAlgorithm', $value);
    }

    /**
     * Completed for the 3-steps flow, obtained from the validation phase.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 05
     */
    public function getEci(): ?string
    {
        return $this->_getString('eci');
    }

    /**
     * Completed for the 3-steps flow, obtained from the validation phase.
     *
     * @optional
     *
     * @return $this
     *
     * @example 05
     */
    public function setEci(?string $value): self
    {
        return $value === null ? $this->_unset('eci') : $this->_set('eci', $value);
    }

    /**
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 494330
     */
    public function getMerchantAcquirerBin(): ?string
    {
        return $this->_getString('merchantAcquirerBin');
    }

    /**
     * @optional
     *
     * @return $this
     *
     * @example 494330
     */
    public function setMerchantAcquirerBin(?string $value): self
    {
        return $value === null ? $this->_unset('merchantAcquirerBin') : $this->_set('merchantAcquirerBin', $value);
    }

    /**
     * Completed for the 3-steps flow, obtained from the validation phase.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example RExDQXMtS05EJTt6VlBNRnxdOkY=
     */
    public function getXid(): ?string
    {
        return $this->_getString('xid');
    }

    /**
     * Completed for the 3-steps flow, obtained from the validation phase.
     *
     * @optional
     *
     * @return $this
     *
     * @example RExDQXMtS05EJTt6VlBNRnxdOkY=
     */
    public function setXid(?string $value): self
    {
        return $value === null ? $this->_unset('xid') : $this->_set('xid', $value);
    }

    /**
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example VALIDATED
     */
    public function getStatus(): ?string
    {
        return $this->_getString('status');
    }

    /**
     * @optional
     *
     * @return $this
     *
     * @example VALIDATED
     */
    public function setStatus(?string $value): self
    {
        return $value === null ? $this->_unset('status') : $this->_set('status', $value);
    }

    /**
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getVendorcode(): ?string
    {
        return $this->_getString('vendorcode');
    }

    /**
     * @optional
     *
     * @return $this
     */
    public function setVendorcode(?string $value): self
    {
        return $value === null ? $this->_unset('vendorcode') : $this->_set('vendorcode', $value);
    }

    /**
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 2.1.0
     */
    public function getVersion(): ?string
    {
        return $this->_getString('version');
    }

    /**
     * @optional
     *
     * @return $this
     *
     * @example 2.1.0
     */
    public function setVersion(?string $value): self
    {
        return $value === null ? $this->_unset('version') : $this->_set('version', $value);
    }
}
