<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity\Cancel;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-operations-operationId-cancels
 */
class Request extends Entity
{
    /**
     * Free text message available to describe the rationale of the cancel.
     *
     * @optional
     * Maximum length: 255
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @example refund executed by mistake
     */
    public function getDescription(): ?string
    {
        return $this->_getString('description');
    }

    /**
     * Free text message available to describe the rationale of the cancel.
     *
     * @optional
     * Maximum length: 255
     *
     * @return $this
     *
     * @example refund executed by mistake
     */
    public function setDescription(?string $value): self
    {
        return $value === null ? $this->_unset('description') : $this->_set('description', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
