<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity\Webhook;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/notifica#tab_body
 */
class Request extends Entity
{
    /**
     * Id of the event.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 554ccc00-28fb-4344-a3fa-4bb8d1999bd5
     */
    public function getEventId(): ?string
    {
        return $this->_getString('eventId');
    }

    /**
     * Id of the event.
     *
     * @optional
     *
     * @return $this
     *
     * @example 554ccc00-28fb-4344-a3fa-4bb8d1999bd5
     */
    public function setEventId(?string $value): self
    {
        return $value === null ? $this->_unset('eventId') : $this->_set('eventId', $value);
    }

    /**
     * Event time in ISO 8601 format
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 1661995200
     */
    public function getEventTime(): ?string
    {
        return $this->_getString('eventTime');
    }

    /**
     * Event time in ISO 8601 format
     *
     * @optional
     *
     * @return $this
     *
     * @example 1661995200
     */
    public function setEventTime(?string $value): self
    {
        return $value === null ? $this->_unset('eventTime') : $this->_set('eventTime', $value);
    }

    /**
     * Token received in the payment initialization phase. Used to detect the notification comes from the payment gateway.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example 2f0ea5059b41414ca3744fe672327d85
     */
    public function getSecurityToken(): ?string
    {
        return $this->_getString('securityToken');
    }

    /**
     * Token received in the payment initialization phase. Used to detect the notification comes from the payment gateway.
     *
     * @optional
     *
     * @return $this
     *
     * @example 2f0ea5059b41414ca3744fe672327d85
     */
    public function setSecurityToken(?string $value): self
    {
        return $value === null ? $this->_unset('securityToken') : $this->_set('securityToken', $value);
    }

    /**
     * Object containing operation detail.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getOperation(): ?\MLocati\Nexi\Entity\Operation
    {
        return $this->_getEntity('operation', \MLocati\Nexi\Entity\Operation::class);
    }

    /**
     * Object containing operation detail.
     *
     * @optional
     *
     * @return $this
     */
    public function setOperation(?\MLocati\Nexi\Entity\Operation $value): self
    {
        return $value === null ? $this->_unset('operation') : $this->_set('operation', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
