<?php

declare(strict_types=1);

namespace MLocati\Nexi\Dictionary;

use ReflectionClass;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * List of ISO 639-2 codes of the languages supported by Nexi.
 */
class Language
{
    /**
     * Arabic
     *
     * @var string
     */
    const ID_ARA = 'ara';

    /**
     * German
     *
     * @var string
     */
    const ID_DEU = 'deu';

    /**
     * Greek
     *
     * @var string
     */
    const ID_ELL = 'ell';

    /**
     * English
     *
     * @var string
     */
    const ID_ENG = 'eng';

    /**
     * French
     *
     * @var string
     */
    const ID_FRA = 'fra';

    /**
     * Italian
     *
     * @var string
     */
    const ID_ITA = 'ita';

    /**
     * Japanese
     *
     * @var string
     */
    const ID_JPN = 'jpn';

    /**
     * Portoguese
     *
     * @var string
     */
    const ID_POR = 'por';

    /**
     * Russian
     *
     * @var string
     */
    const ID_RUS = 'rus';

    /**
     * Spanish
     *
     * @var string
     */
    const ID_SPA = 'spa';

    /**
     * Zhuang, Chuang
     *
     * @var string
     */
    const ID_ZHA = 'zha';

    /**
     * @return string[]
     */
    public function getAvailableIDs(): array
    {
        $result = [];
        $class = new ReflectionClass($this);
        foreach ($class->getConstants() as $name => $value) {
            if (strpos($name, 'ID_') === 0 && is_string($value)) {
                $result[] = $value;
            }
        }

        return $result;
    }
}
