<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity\CreateReservation;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-reservations
 */
class Response extends Entity
{
    /**
     * Merchant reservation id, unique in the merchant domain
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @example btid2384983
     */
    public function getReservationId(): ?string
    {
        return $this->_getString('reservationId');
    }

    /**
     * Merchant reservation id, unique in the merchant domain
     *
     * @optional
     *
     * @return $this
     *
     * @example btid2384983
     */
    public function setReservationId(?string $value): self
    {
        return $value === null ? $this->_unset('reservationId') : $this->_set('reservationId', $value);
    }
}
