<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity\ListSupportedPaymentMethods;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-payment_methods
 */
class Response extends Entity
{
    /**
     * Array of objects containing the payment methods enabled on the terminal.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @return \MLocati\Nexi\XPayWeb\Entity\PaymentMethod[]|null
     */
    public function getPaymentMethods(): ?array
    {
        return $this->_getEntityArray('paymentMethods', \MLocati\Nexi\XPayWeb\Entity\PaymentMethod::class);
    }

    /**
     * Array of objects containing the payment methods enabled on the terminal.
     *
     * @param \MLocati\Nexi\XPayWeb\Entity\PaymentMethod[]|null $value
     *
     * @optional
     *
     * @return $this
     */
    public function setPaymentMethods(?array $value): self
    {
        return $value === null ? $this->_unset('paymentMethods') : $this->_setEntityArray('paymentMethods', \MLocati\Nexi\XPayWeb\Entity\PaymentMethod::class, $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
