<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity\ListSupportedPaymentMethods;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/post-payment_methods
 */
class Response extends Entity
{
    /**
     * Array of objects containing the payment methods enabled on the terminal.
     *
     * @optional
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     *
     * @return \MLocati\Nexi\Entity\PaymentMethod[]|null
     */
    public function getPaymentMethods(): ?array
    {
        return $this->_getEntityArray('paymentMethods', \MLocati\Nexi\Entity\PaymentMethod::class);
    }

    /**
     * Array of objects containing the payment methods enabled on the terminal.
     *
     * @param \MLocati\Nexi\Entity\PaymentMethod[]|null $value
     *
     * @optional
     *
     * @return $this
     */
    public function setPaymentMethods(?array $value): self
    {
        return $value === null ? $this->_unset('paymentMethods') : $this->_setEntityArray('paymentMethods', \MLocati\Nexi\Entity\PaymentMethod::class, $value);
    }
}
