<?php

declare(strict_types=1);

namespace MLocati\Nexi\XPayWeb\Entity\FindReservations;

use MLocati\Nexi\XPayWeb\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-reservations
 */
class Response extends Entity
{
    /**
     * @optional
     *
     * @throws \MLocati\Nexi\XPayWeb\Exception\WrongFieldType
     *
     * @return \MLocati\Nexi\XPayWeb\Entity\Reservation[]|null
     */
    public function getReservation(): ?array
    {
        return $this->_getEntityArray('reservation', \MLocati\Nexi\XPayWeb\Entity\Reservation::class);
    }

    /**
     * @param \MLocati\Nexi\XPayWeb\Entity\Reservation[]|null $value
     *
     * @optional
     *
     * @return $this
     */
    public function setReservation(?array $value): self
    {
        return $value === null ? $this->_unset('reservation') : $this->_setEntityArray('reservation', \MLocati\Nexi\XPayWeb\Entity\Reservation::class, $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\XPayWeb\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
        ];
    }
}
