<?php

declare(strict_types=1);

namespace MLocati\Nexi\Entity\GetService;

use MLocati\Nexi\Entity;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

/**
 * @see https://developer.nexi.it/en/api/get-services
 */
class Query extends Entity implements \MLocati\Nexi\Service\QueryEntityInterface
{
    use \MLocati\Nexi\Service\QueryEntityTrait;

    /**
     * The unique identifier for service name in nexi ecosystem.
     *
     * @required
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getServiceName(): ?string
    {
        return $this->_getString('serviceName');
    }

    /**
     * The unique identifier for service name in nexi ecosystem.
     *
     * @required
     *
     * @return $this
     */
    public function setServiceName(string $value): self
    {
        return $this->_set('serviceName', $value);
    }

    /**
     * The unique identifier for the terminal.
     *
     * @required
     *
     * @throws \MLocati\Nexi\Exception\WrongFieldType
     */
    public function getTerminalId(): ?string
    {
        return $this->_getString('terminalId');
    }

    /**
     * The unique identifier for the terminal.
     *
     * @required
     *
     * @return $this
     */
    public function setTerminalId(string $value): self
    {
        return $this->_set('terminalId', $value);
    }

    /**
     * {@inheritdoc}
     *
     * @see \MLocati\Nexi\Entity::getRequiredFields()
     */
    protected function getRequiredFields(): array
    {
        return [
            'serviceName' => true,
            'terminalId' => true,
        ];
    }
}
