<?php

declare(strict_types=1);

namespace MLocati\Nexi;

/*
 * WARNING: DO NOT EDIT THIS FILE
 * It has been generated automaticlly from a template.
 * Edit the template instead.
 */

interface Configuration
{
    /**
     * This is the default URL to be used for tests.
     *
     * @var string
     */
    const DEFAULT_BASEURL_TEST = 'https://stg-ta.nexigroup.com/api/phoenix-0.0/psp/api/v1';

    /**
     * This is the default URL to be used in production.
     *
     * @var string
     */
    const DEFAULT_BASEURL_PRODUCTION = 'https://xpay.nexigroup.com/api/phoenix-0.0/psp/api/v1/';

    /**
     * Get the API key.
     */
    public function getBaseURL(): string;

    /**
     * Get the API key.
     */
    public function getApiKey(): string;
}
